---
- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - group:
        name: porecampers
        state: present

- hosts: vm1grp
  become: yes
  become_method: sudo
  tasks:
    - user:
        name: "{{ item }}"
        shell: /bin/bash
        groups: porecampers,users
        home: "/vol_c/{{ item }}"
        append: yes
        password: "SHA-1"
      with_items:
        - 40group1
        - 40group2
        - 40group3
        - 40group4
        - 40group5
        - testuser

- hosts: vm1grp 
  become: yes
  become_method: sudo
  tasks:
     - blockinfile:
         path: "/vol_c/{{ item }}/.bashrc"
         block: |
                source /etc/profile.d/porecamp
       with_items:
         - 40group1
         - 40group2
         - 40group3
         - 40group4
         - 40group5
         - testuser

- hosts: vm2grp
  become: yes
  become_method: sudo
  tasks:
    - user:
        name: "{{ item }}"
        shell: /bin/bash
        groups: porecampers,users
        append: yes
        home: "/vol_c/{{ item }}"
        password: "SHA-1"
      with_items:
        - 49group1
        - 49group2
        - 49group3
        - 49group4
        - 49group5

- hosts: vm2grp
  become: yes
  become_method: sudo
  tasks:
     - blockinfile:
         path: "/vol_c/{{ item }}/.bashrc"
         block: |
                source /etc/profile.d/porecamp
       with_items:
         - 49group1
         - 49group2
         - 49group3
         - 49group4
         - 49group5

- hosts: vm3grp
  become: yes
  become_method: sudo
  tasks:
    - user:
        name: "{{ item }}"
        shell: /bin/bash
        groups: porecampers,users
        append: yes
        home: "/vol_c/{{ item }}"
        password: "SHA-1"
      with_items:
        - 36group1
        - 36group2
        - 36group3
        - 36group4
        - 36group5

- hosts: vm4grp
  become: yes
  become_method: sudo
  tasks:
    - user:
        name: "{{ item }}"
        shell: /bin/bash
        groups: porecampers,users
        append: yes
        home: "/vol_c/{{ item }}"
        password: "SHA-1"
      with_items:
        - 146group1
        - 146group2
        - 146group3
        - 146group4
        - 146group5
        - nickloman
        - mickwatson

- hosts: vm5grp
  become: yes
  become_method: sudo
  tasks:
    - user:
        name: "{{ item }}"
        shell: /bin/bash
        groups: porecampers,users
        append: yes
        home: "/vol_c/{{ item }}"
        password: "SHA-1"
      with_items:
        - 146group1
        - 146group2
        - 146group3
        - 146group4
        - 146group5
        - nickloman
        - mickwatson

- hosts: vm5grp
  become: yes
  become_method: sudo
  tasks:
    - user:
        name: "{{ item }}"
        shell: /bin/bash
        groups: porecampers,users
        append: yes
        home: "/vol_c/{{ item }}"
        password: "SHA-1"
      with_items:
        - 146group1
        - 146group2
        - 146group3
        - 146group4
        - 146group5
        - 18group1
        - 18group2
        - 40group1
        - 40group2
        - 40group3
        - 40group4
        - 40group5
        - nickloman
        - mickwatson

- hosts: vm6grp
  become: yes
  become_method: sudo
  tasks:
    - user:
        name: "{{ item }}"
        shell: /bin/bash
        groups: porecampers,users
        append: yes
        home: "/vol_c/{{ item }}"
        password: "SHA-1"
      with_items:
        - 146group1
        - 146group2
        - 146group3
        - 146group4
        - 146group5
        - 47group1
        - 47group2
        - 47group3
        - 49group1
        - 49group2
        - 49group3
        - 49group4
        - 49group5
        - nickloman
        - mickwatson


